#! /usr/local/bin/python

import argparse
import collections
import itertools
import unicodecsv

desc = 'Extract the transaction section of a Shoeboxed CSV export.'
ap = argparse.ArgumentParser(description=desc)

# desc = 'The source CSV file. If omitted will read from STDIN.'
desc = 'The source CSV file.'
ap.add_argument('source_csv', metavar='FILE', help=desc)

# to be done later
# desc = 'The output CSV file. If omitted will write to STDOUT.'

args = ap.parse_args()

# assume that the transaction section header is a record having at least:
#   Date, Store, Total (USD), Payment Type, Categories, Link
# if there is no such record then the export format has changed
# and we don't have the requisite fields to proceed
def is_transaction_prefix(record):
    mark = {'Date', 'Store', 'Total (USD)', 'Payment Type', 'Categories', 'Link'}
    return set(record).issuperset(mark)

# the transaction section is followed by a blank record
def is_transaction_suffix(record):
    return len([f for f in record if f]) == 0

with open(args.source_csv, 'r') as f:
    with open('cleaned.csv', 'w') as w:
        reader = itertools.takewhile(lambda x: not is_transaction_suffix(x),
                 itertools.dropwhile(lambda x: not is_transaction_prefix(x),
                 unicodecsv.reader(f)))

        # we want to fail here if no records match is_transaction_prefix
        header = reader.next()

        writer = unicodecsv.writer(w)
        writer.writerow(header)
        writer.writerows(reader)
